### ISSUE TITLE
Teams Webhooks

### ISSUE THREAD

**Issue by retreif** [BinaryDefense/log4j-honeypot-flask#7]
How much testing did you do with Teams webhooks?  I wasn't able to run the honeypot in Docker with the Teams string and even setting the environmental variables and just running the app it doesn't seem to work.   My skill level with Docker and Linux in general is novice.  If this is the wrong place for this I apologize in advance.

**Comment by 4Nzic-fiddler** [comment]
I only ran one test for Teams and since then I’ve been running it in
production with Mattermost. However, the code and message format is exactly
the same so it should work. I can help you test to see what is wrong if you
like.

**Comment by retreif** [comment]
I moved all the config into the script and have it working.  I'll work my way back through to see what I was doing wrong.

**Comment by 4Nzic-fiddler** [comment]
Oh good! Glad you have it working now. It must be something about the
environment variables misspelled or not getting set.

**Comment by 4Nzic-fiddler** [comment]
Not an issue with the code
